spring:
  application:
    name: LibraryApi

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: none

server:
  port: 8080

springdoc:
  swagger-ui:
    path: doc
  api-docs:
    path: /api-docs